data_path:
  raw_data: data/raw/
  raw_images: data/raw/images/
  raw_texts: data/raw/texts/
  processed_data: data/processed/
  train_data: data/processed/train/
  val_data: data/processed/val/
  test_data: data/processed/test/

kaggle_setup:
  images_folder: preprocessed_images/
  text_file: text/evaluate_60k_data_balanced_preprocessed.csv