memory_monitor:
  max_ram_percent: 95
  warn_threshold_percent: 90

cpu_monitor:
  cpu_memory_check_interval: 5
  warn_threshold_percent: 90
  max_cpu_memory_percent: 95

gpu_monitor:
  gpu_memory_check_interval: 5
  warn_threshold_percent: 90
  max_gpu_memory_percent: 95